name: Compilar EXE Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4       # Actualizado a v4
    
    - name: Instalar Python
      uses: actions/setup-python@v5   # Actualizado a v5
      with:
        python-version: '3.10' 
        
    - name: Instalar Dependencias
      run: |
        pip install -r requirements.txt
        
    - name: Compilar con PyInstaller
      run: |
        pyinstaller --noconsole --onefile --windowed --name="IngenieriaCPD_v15" cpd_desktop.py
        
    - name: Subir el EXE resultante
      uses: actions/upload-artifact@v4 # <--- ESTA ES LA CORRECCIÃ“N CLAVE (v4)
      with:
        name: Mi_Programa_CPD
        path: dist/IngenieriaCPD_v15.exe
        overwrite: true
